version: "3"
services:
  bitrix_mysql:
    container_name: 'bitrix_mysql'
    image: alex19pov31/bitrix-mariadb
    expose:
      - "3306"
    volumes:
      - ./.docker/mysql/conf/etc/my.cnf.d/custom.cnf:/etc/my.cnf.d/mariadb-server.cnf:ro
      - db-data:/var/lib/mysql
      - tmp:/var/tmp
      - pid:/run
    env_file: ./.docker/.env
    shm_size: 2G
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    read_only: true
  bitrix_php71-fpm:
    container_name: 'bitrix_php71'
    image: alex19pov31/bitrix-php71-fpm
    working_dir: /home/www/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    links:
      - bitrix_mysql
      - bitrix_memcached
    depends_on:
      - bitrix_mysql
    volumes:
      - pid:/var/run
      - tmp:/tmp
      - tmp:$HOME/.composer/cache:rw
      - ../:/home/www/bitrix:rw
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/z-custom.ini:ro
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./.docker/php/msmtprc:/etc/msmtprc
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    read_only: false
  bitrix_php72-fpm:
    container_name: 'bitrix_php72'
    image: alex19pov31/bitrix-php72-fpm
    working_dir: /home/www/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    links:
      - bitrix_mysql
      - bitrix_memcached
    depends_on:
      - bitrix_mysql
    volumes:
      - pid:/var/run
      - tmp:/tmp
      - tmp:$HOME/.composer/cache:rw
      - ../:/home/www/bitrix:rw
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/z-custom.ini:ro
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./.docker/php/msmtprc:/etc/msmtprc
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    read_only: false
  bitrix_php73-fpm:
    container_name: 'bitrix_php73'
    image: alex19pov31/bitrix-php73-fpm
    working_dir: /home/www/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    links:
      - bitrix_mysql
      - bitrix_memcached
    depends_on:
      - bitrix_mysql
    volumes:
      - pid:/var/run
      - tmp:/tmp
      - tmp:$HOME/.composer/cache:rw
      - ../:/home/www/bitrix:rw
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/z-custom.ini:ro
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./.docker/php/msmtprc:/etc/msmtprc
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    read_only: true
  bitrix_php74-fpm:
    container_name: 'bitrix_php74'
    image: alex19pov31/bitrix-php74-fpm
    working_dir: /home/www/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    links:
      - bitrix_mysql
      - bitrix_memcached
    depends_on:
      - bitrix_mysql
    volumes:
      - pid:/var/run
      - tmp:/tmp
      - tmp:$HOME/.composer/cache:rw
      - ../:/home/www/bitrix:rw
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/z-custom.ini:ro
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./.docker/php/msmtprc:/etc/msmtprc
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    read_only: true
  bitrix_php8-fpm:
    container_name: 'bitrix_php8'
    image: alex19pov31/bitrix-php8-fpm
    working_dir: /home/www/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    links:
      - bitrix_mysql
      - bitrix_memcached
    depends_on:
      - bitrix_mysql
    volumes:
      - pid:/var/run
      - tmp:/tmp
      - tmp:$HOME/.composer/cache:rw
      - ../:/home/www/bitrix:rw
      - ./.docker/php/custom_php8.ini:/usr/local/etc/php/conf.d/z-custom.ini:ro
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./.docker/php/msmtprc:/etc/msmtprc
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    read_only: true
  bitrix_php56-fpm:
    container_name: 'bitrix_php56'
    image: alex19pov31/bitrix-php56-fpm
    working_dir: /home/www/
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    links:
      - bitrix_mysql
      - bitrix_memcached
    depends_on:
      - bitrix_mysql
    volumes:
      - pid:/var/run
      - tmp:/tmp
      - tmp:$HOME/.composer/cache:rw
      - ../:/home/www/bitrix:rw
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/z-custom.ini:ro
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./.docker/php/msmtprc:/etc/msmtprc
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
    read_only: true
  bitrix_nginx:
    container_name: 'bitrix_nginx'
    image: nginx:alpine
    links:
      - "bitrix_php71-fpm:bitrix_php71-fpm"
      - "bitrix_php72-fpm:bitrix_php72-fpm"
      - "bitrix_php73-fpm:bitrix_php73-fpm"
      - "bitrix_php74-fpm:bitrix_php74-fpm"
      - "bitrix_php8-fpm:bitrix_php8-fpm"
      - "bitrix_php56-fpm:bitrix_php56-fpm"
    depends_on:
      - bitrix_php71-fpm
      - bitrix_php72-fpm
      - bitrix_php73-fpm
      - bitrix_php74-fpm
      - bitrix_php8-fpm
      - bitrix_php56-fpm
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "443:443"
    volumes:
      - tmp:/var/cache/nginx:rw
      - pid:/var/run:rw
      - ./.docker/nginx/conf/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/conf/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./.docker/nginx/conf/etc/nginx/templates:/etc/nginx/templates:ro
      - ../:/home/www/bitrix:rw
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    read_only: true
  bitrix_memcached:
    container_name: 'bitrix_memcached'
    image: memcached:alpine
    command: ["memcached", "-m", "256", "-p", "11211"]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
    read_only: true
volumes:
  composer-data:
  db-data:
  tmp:
  pid:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16